services:

  mysql:
    image: mysql:8.4
    container_name: reserva-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  discovery-server:
    build:
      context: ./discovery-server/discovery-server
      dockerfile: Dockerfile
    container_name: reserva-discovery-server
    ports:
      - "8761:8761"
    environment:
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"

  ms-usuarios:
    build:
      context: ./ms-usuarios/ms-usuarios
      dockerfile: Dockerfile
    container_name: reserva-ms-usuarios
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
      discovery-server:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/reserva_usuarios_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/

  ms-salas:
    build:
      context: ./ms-salas/ms-salas
      dockerfile: Dockerfile
    container_name: reserva-ms-salas
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
      discovery-server:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/reserva_salas_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/

  ms-reservas:
    build:
      context: ./ms-reservas/ms-reservas
      dockerfile: Dockerfile
    container_name: reserva-ms-reservas
    ports:
      - "8083:8083"
    depends_on:
      mysql:
        condition: service_healthy
      discovery-server:
        condition: service_started
      ms-usuarios:
        condition: service_started
      ms-salas:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/reserva_reservas_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/

  api-gateway:
    build:
      context: ./api-gateway/api-gateway
      dockerfile: Dockerfile
    container_name: reserva-api-gateway
    ports:
      - "8080:8080"
    depends_on:
      discovery-server:
        condition: service_started
      ms-usuarios:
        condition: service_started
      ms-salas:
        condition: service_started
      ms-reservas:
        condition: service_started
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/

volumes:
  mysql_data: